name: pypi_upload

on:
  release:
    types: [created]

jobs:
  upload:
    name: PyPI Upload
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install latest pip, setuptools, build, twine
      run: |
        python -m pip install --upgrade pip setuptools build twine
    - name: Build sdist + wheel
      run: |
        python -m build
    - name: Upload to PyPI via Twine
      env:
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        twine upload --verbose -u '__token__' dist/*